/*
SQLyog Enterprise - MySQL GUI v7.15 
MySQL - 5.6.17 : Database - SigosWeb
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE /*!32312 IF NOT EXISTS*/`SigosWeb` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `SigosWeb`;


/*Table structure for table `UNIDADE` */

DROP TABLE IF EXISTS `UNIDADE`;

CREATE TABLE `UNIDADE` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Data for the table `UNIDADE` */

insert  into `UNIDADE`(`_id`,`NOME`) values (1,'Guama'),(2,'Altamira');

/*Table structure for table `SETOR` */

DROP TABLE IF EXISTS `SETOR`;

CREATE TABLE `SETOR` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `UNIDADE` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_SETOR_UNIDADE_idx` (`UNIDADE`),
  CONSTRAINT `FK_SETOR_UNIDADE` FOREIGN KEY (`UNIDADE`) REFERENCES `UNIDADE` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

/*Data for the table `SETOR` */

insert  into `SETOR`(`_id`,`NOME`,`UNIDADE`) values (1,'ICB',1),(2,'ITEC',1),(3,'Ginasio',1),(4,'Biblioteca',1),(5,'Biblioteca',2),(6,'Bloco A',2);


/*Table structure for table `USUARIO` */

DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(200) NOT NULL,
  `TELEFONE` varchar(14) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `SETOR` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_USUARIO_SETOR_idx` (`SETOR`),
  CONSTRAINT `FK_USUARIO_SETOR` FOREIGN KEY (`SETOR`) REFERENCES `SETOR` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `USUARIO` */

/*Table structure for table `ESTUDANTE` */

DROP TABLE IF EXISTS `ESTUDANTE`;

CREATE TABLE `ESTUDANTE` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `MATRICULA` varchar(20) NOT NULL,
  `USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_ESTUDANTE_USUARIO_idx` (`USUARIO`),
  CONSTRAINT `FK_ESTUDANTE_USUARIO` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIO` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `ESTUDANTE` */

/*Table structure for table `FUNCIONARIO` */

DROP TABLE IF EXISTS `FUNCIONARIO`;

CREATE TABLE `FUNCIONARIO` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `SIAPE` varchar(20) NOT NULL,
  `USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_FUNCIONARIO_USUARIO_idx` (`USUARIO`),
  CONSTRAINT `FK_FUNCIONARIO_USUARIO` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIO` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `FUNCIONARIO` */

/*Table structure for table `OUTRO` */

DROP TABLE IF EXISTS `OUTRO`;

CREATE TABLE `OUTRO` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `CPF` varchar(11) NOT NULL,
  `USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_OUTRO_USUARIO_idx` (`USUARIO`),
  CONSTRAINT `FK_OUTRO_USUARIO` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIO` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `OUTRO` */

/*Table structure for table `OCORRENCIA_TIPO` */

DROP TABLE IF EXISTS `OCORRENCIA_TIPO`;

CREATE TABLE `OCORRENCIA_TIPO` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Data for the table `OCORRENCIA_TIPO` */

insert  into `OCORRENCIA_TIPO`(`_id`,`NOME`) values (1,'Assalto'),(2,'Furto'),(3,'Depredação'),(4,'Invasão'),(5,'Pessoa Estranha');



/*Table structure for table `PAPEL` */

DROP TABLE IF EXISTS `PAPEL`;

CREATE TABLE `PAPEL` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

/*Data for the table `PAPEL` */

insert  into `PAPEL`(`_id`,`NOME`) values (1,'Vítima'),(2,'Testemunha');


/*Table structure for table `OCORRENCIA` */

DROP TABLE IF EXISTS `OCORRENCIA`;

CREATE TABLE `OCORRENCIA` (
  `_id` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` text NOT NULL,
  `LOCAL` varchar(200) DEFAULT NULL,
  `PAPEL` int(11) NOT NULL,
  `TIPO_OCORRENCIA` int(11) DEFAULT NULL,
  `SETOR` int(11) DEFAULT NULL,
  `USUARIO` int(11) DEFAULT NULL,
  PRIMARY KEY (`_id`),
  KEY `FK_OCORRENCIA_TIPO_OCORRENCIA_idx` (`TIPO_OCORRENCIA`),
  KEY `FK_OCORRENCIA_SETOR_idx` (`SETOR`),
  KEY `FK_OCORRENCIA_USUARIO_idx` (`USUARIO`),
  KEY `FK_OCORRENCIA_PAPEL_idx` (`PAPEL`),
  CONSTRAINT `FK_OCORRENCIA_PAPEL` FOREIGN KEY (`PAPEL`) REFERENCES `PAPEL` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_OCORRENCIA_SETOR` FOREIGN KEY (`SETOR`) REFERENCES `SETOR` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_OCORRENCIA_TIPO_OCORRENCIA` FOREIGN KEY (`TIPO_OCORRENCIA`) REFERENCES `OCORRENCIA_TIPO` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_OCORRENCIA_USUARIO` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIO` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `OCORRENCIA` */
