//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SigosWebEntities : DbContext
{
    public SigosWebEntities() : base("name=SigosWebEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Estudante> Estudante { get; set; }
    public virtual DbSet<Funcionario> Funcionario { get; set; }
    public virtual DbSet<Ocorrencia> Ocorrencia { get; set; }
    public virtual DbSet<Outro> Outro { get; set; }
    public virtual DbSet<Papel> Papel { get; set; }
    public virtual DbSet<Setor> Setor { get; set; }
    public virtual DbSet<TipoOcorrencia> TipoOcorrencia { get; set; }
    public virtual DbSet<Unidade> Unidade { get; set; }
    public virtual DbSet<Usuario> Usuario { get; set; }

}
